language: groovy

sudo: required

group: deprecated-2017Q2

branches:
  only:
    - master

services:
    - docker

# Cache the gradle wrapper to avoid downloading each time
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

before_install:
    - make plugins
    - make requirements
    - cp local_env.sh.sample local_env.sh && source local_env.sh
    - make build
    - make run

script:
    - make quality
    - make healthcheck
    - make e2e
