---
CLOUDS:
    - NAME: 'aws-cloud'
      ACCESS_KEY_ID: 'accessKey'
      SECRET_ACCESS_KEY: 'secretKey'
      USE_INSTANCE_PROFILE_FOR_CREDS: false
      REGION: 'us-east-1'
      EC2_PRIVATE_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQCtDBNLA5EjXpLw5/5e3vATGlrOMf3PAbo+SMNhMoHj1BOm9T1r
        iMPrq8gPytA9hDpjIHcwWKBPkLwswk/2LR9HgygB8o2qIEUlMOOsMqLXV747k7w4
        fyeJZfNgPaC2PCwT7Q3uzoguFIs3XwwMR6WqrFfI5qDN3okcrhaBLvjNpwIDAQAB
        AoGAOrqYaaMCRQC52ezCVaxPygvtuYEZ5IFvlefX90rO7mVxbf5ZI/+8jmU0drec
        SORxdGb2TIAnmBlE4+Pmg2P48xskPnIe6SqQzkfq6BXJAyUnOqyWkHYM/WIEzRwQ
        yZFW+tBjqACej27JJ14IniptBiRvOZzn1CJf94Iku51ooJECQQDe7Q9qtFtWgptT
        dU92l38NLQbctnO1wrhhBDkDwQTduMY+v5S6Wei2I+ph1V8nbSThNfAQDXo27tnW
        47lPzNmVAkEAxriR0k0mcOHEKkGubD79bm1juQ6Ymux6G+fR7cXBCzSemgshYOvb
        7ITs0qx2/ra1hOguvtlLS9h782T9NNMTSwJBAK++T9MdUIyI9o77AqRJlr36a1iA
        9gOq+NRzEcel2YI6cv9w5X1r+AvvkI2EOznHz7VEYnclSN4Zut6wNJ12r2kCQDaH
        73wGL8ZKLcpqu7J4lpL28aaWmsnompmNw827tn2csukSpNYz4uXElDg7m2vKN4WB
        MVKtzjvB7EGeNN2KDoECQFXkKk992K4DDIU4+r0KC1UfyYbrR9mqP+6GHamwy3GE
        t/o3AjOO9Paoe7l15GLl0uOT65HCIg+kBnbHGdilxz8=
        -----END RSA PRIVATE KEY-----
      INSTANCE_CAP: '250'
      AMIS:
          - AMI_ID: 'ami1'
            AVAILABILITY_ZONE: 'zone1'
            SPOT_CONFIG:
                SPOT_MAX_BID_PRICE: '100'
                SPOT_INSTANCE_BID_TYPE: 'persistent'
            SECURITY_GROUPS: 'security1'
            REMOTE_FS_ROOT: '/root/stuff1'
            SSH_PORT: '22'
            INSTANCE_TYPE: 'm3.large'
            LABEL_STRING: 'label1'
            MODE: 'normal'
            DESCRIPTION: 'description1'
            INIT_SCRIPT_PATH: 'init-configs/ec2/init_script.sh'
            TEMP_DIR: 'tmp1'
            USER_DATA: 'user-data1'
            NUM_EXECUTORS: '10'
            REMOTE_ADMIN: 'root-admin'
            ROOT_COMMAND_PREFIX: 'root-command'
            JVM_OPTIONS: 'jvm-option-1'
            STOP_ON_TERMINATE: false
            SUBNET_ID: 'subnet-123'
            TAGS:
                - NAME: 'name1'
                  VALUE: 'value1'
                - NAME: 'name2'
                  VALUE: 'value2'
            IDLE_TERMINATION_MINUTES: '8'
            USE_PRIVATE_DNS_NAME: true
            INSTANCE_CAP: '4'
            IAM_INSTANCE_PROFILE: 'arn:aws:iam::123:dummy_worker1'
            USE_EPHEMERAL_DEVICES: false
            LAUNCH_TIMEOUT: '60'
          - AMI_ID: 'ami2'
            AVAILABILITY_ZONE: 'zone2'
            SPOT_CONFIG:
                SPOT_MAX_BID_PRICE: '200'
                SPOT_INSTANCE_BID_TYPE: 'one-time'
            SECURITY_GROUPS: 'security2'
            REMOTE_FS_ROOT: '/root/stuff2'
            SSH_PORT: '22'
            INSTANCE_TYPE: 't1.micro'
            LABEL_STRING: 'label2'
            MODE: 'normal'
            DESCRIPTION: 'description2'
            INIT_SCRIPT_PATH: 'init-configs/ec2/init_script.sh'
            TEMP_DIR: 'tmp2'
            USER_DATA: 'user-data2'
            NUM_EXECUTORS: '10'
            REMOTE_ADMIN: 'root-admin'
            ROOT_COMMAND_PREFIX: 'root-command'
            JVM_OPTIONS: 'jvm-option-1'
            STOP_ON_TERMINATE: false
            SUBNET_ID: 'subnet-123'
            TAGS:
                - NAME: 'name1'
                  VALUE: 'value1'
                - NAME: 'name2'
                  VALUE: 'value2'
            IDLE_TERMINATION_MINUTES: '8'
            USE_PRIVATE_DNS_NAME: true
            INSTANCE_CAP: '4'
            IAM_INSTANCE_PROFILE: 'arn:aws:iam::123:dummy_worker2'
            USE_EPHEMERAL_DEVICES: false
            LAUNCH_TIMEOUT: '60'
