---
CLOUDS:
    - NAME: 'aws-cloud'
      CREDENTIAL_ID: 'ec2CloudConfig'
      USE_INSTANCE_PROFILE_FOR_CREDS: false
      REGION: 'us-east-1'
      EC2_PRIVATE_KEY_PATH: '/var/lib/jenkins/init-configs/ec2/id_rsa'
      INSTANCE_CAP: '250'
      AMIS:
          - AMI_ID: 'ami1'
            AMI_TYPE:
                ROOT_COMMAND_PREFIX: ''
                SLAVE_COMMAND_PREFIX: ''
                REMOTE_SSH_PORT: '22'
            AVAILABILITY_ZONE: 'zone1'
            SPOT_CONFIG:
                SPOT_MAX_BID_PRICE: '100'
                SPOT_INSTANCE_BID_TYPE: 'persistent'
            SECURITY_GROUPS: 'security1'
            REMOTE_FS_ROOT: '/root/stuff1'
            INSTANCE_TYPE: 'm3.large'
            EBS_OPTIMIZED: false
            LABEL_STRING: 'label1'
            MODE: 'normal'
            DESCRIPTION: 'description1'
            INIT_SCRIPT_PATH: '/var/lib/jenkins/init-configs/ec2/init_script.sh'
            TEMP_DIR: 'tmp1'
            USER_DATA: 'user-data1'
            NUM_EXECUTORS: '10'
            REMOTE_ADMIN: 'root-admin'
            JVM_OPTIONS: 'jvm-option-1'
            STOP_ON_TERMINATE: false
            SUBNET_ID: 'subnet-123'
            TAGS:
                - NAME: 'name1'
                  VALUE: 'value1'
                - NAME: 'name2'
                  VALUE: 'value2'
            IDLE_TERMINATION_MINUTES: '8'
            USE_PRIVATE_DNS_NAME: true
            INSTANCE_CAP: '4'
            IAM_INSTANCE_PROFILE: 'arn:aws:iam::123:dummy_worker1'
            DELETE_ROOT_ON_TERMINATION: true
            USE_EPHEMERAL_DEVICES: false
            USE_DEDICATED_TENANCY: false
            LAUNCH_TIMEOUT: '60'
            ASSOCIATE_PUBLIC_IP: false
            CUSTOM_DEVICE_MAPPING: ''
            USE_EXTERNAL_SSH_PROCESS: false
            CONNECT_WITH_PUBLIC_IP: false
          - AMI_ID: 'ami2'
            AMI_TYPE:
                ROOT_COMMAND_PREFIX: ''
                SLAVE_COMMAND_PREFIX: ''
                REMOTE_SSH_PORT: '22'
            AVAILABILITY_ZONE: 'zone2'
            SPOT_CONFIG:
                SPOT_MAX_BID_PRICE: '200'
                SPOT_INSTANCE_BID_TYPE: 'one-time'
            SECURITY_GROUPS: 'security2'
            REMOTE_FS_ROOT: '/root/stuff2'
            INSTANCE_TYPE: 't1.micro'
            EBS_OPTIMIZED: true
            LABEL_STRING: 'label2'
            MODE: 'normal'
            DESCRIPTION: 'description2'
            INIT_SCRIPT_PATH: '/var/lib/jenkins/init-configs/ec2/init_script.sh'
            TEMP_DIR: 'tmp2'
            USER_DATA: 'user-data2'
            NUM_EXECUTORS: '10'
            REMOTE_ADMIN: 'root-admin'
            JVM_OPTIONS: 'jvm-option-1'
            STOP_ON_TERMINATE: false
            SUBNET_ID: 'subnet-123'
            TAGS:
                - NAME: 'name1'
                  VALUE: 'value1'
                - NAME: 'name2'
                  VALUE: 'value2'
            IDLE_TERMINATION_MINUTES: '8'
            USE_PRIVATE_DNS_NAME: true
            INSTANCE_CAP: '4'
            IAM_INSTANCE_PROFILE: 'arn:aws:iam::123:dummy_worker2'
            DELETE_ROOT_ON_TERMINATION: true
            USE_EPHEMERAL_DEVICES: false
            USE_DEDICATED_TENANCY: false
            LAUNCH_TIMEOUT: '60'
            ASSOCIATE_PUBLIC_IP: false
            CUSTOM_DEVICE_MAPPING: ''
            USE_EXTERNAL_SSH_PROCESS: false
            CONNECT_WITH_PUBLIC_IP: false
