---
ACCESS_TOKEN: accessTokenString
ADMIN_LIST:
  - admin1
  - admin2
AUTO_CLOSE_FAILED_PRS: false
BLACK_LIST_COMMIT_AUTHOR: ''
BLACK_LIST_LABELS:
  - foo
  - bar
BUILD_LOG_LINES_TO_DISPLAY: 25
CANCEL_BUILD_ON_UPDATE: true
CREDENTIALS_ID: secretFile1
CRON_SCHEDULE: H/5 * * * *
DISPLAY_ERRORS_DOWNSTREAM: true
GITHUB_AUTH: test
MANAGE_WEBHOOKS: false
OK_PHRASE: this is OK to test
PUBLISH_JENKINS_URL: myjenkinsinstance.com
REQUEST_TESTING_PHRASE: retest this PR please
RESULT_MESSAGES:
  - MESSAGE: this is pending
    STATUS: pending
  - MESSAGE: this was a failure
    STATUS: failure
RETEST_PHRASE: please retest
SERVER_API_URL: 'https://api.github.com'
SHARED_SECRET: ''
SIMPLE_STATUS: simple status
SKIP_PHRASE: skip tests
UNSTABLE_AS: pending
USE_COMMENTS: true
USE_DETAILED_COMMENTS: false
WHITE_LIST_PHRASE: add this github user
