---
HISTORY_ROOT_DIR: ""
MAX_HISTORY_ENTRIES: "10"
MAX_DAYS_TO_KEEP_ENTRIES: "15"
MAX_ENTRIES_PER_PAGE: "20"
SKIP_DUPLICATE_HISTORY: true
EXCLUDE_PATTERN: "GhprbTrigger"
SAVE_MODULE_CONFIGURATION: true
SHOW_BUILD_BADGES: "userWithConfigPermission"
EXCLUDED_USERS: "user"
