---
PYTHON_INSTALLATIONS:
    - PYTHON_ALIAS: 'PY_27'
      PYTHON_PATH: '/usr/bin/python2.7'
      PYTHON_PROPERTIES: []
    - PYTHON_ALIAS: 'PY_35'
      PYTHON_PATH: '/usr/bin/python3.5'
      PYTHON_PROPERTIES: []
