---
AGENT_SETTINGS:
    PROTOCOLS:
      - 'JNLP4-connect'
    JNLP_TCP_PORT: 0
OAUTH_SETTINGS:
    GITHUB_WEB_URI: 'https://github.com'
    GITHUB_API_URI: 'https://api.github.com'
    CLIENT_ID: 'clientId'
    CLIENT_SECRET: 'secret'
    SCOPES: 'read:org'
SECURITY_GROUPS:
    # Users with similar permission needs should be grouped
    # into security groups. This can include GH users, teams,
    # orgs, and the anonymous user
    - NAME: 'basic anonymous perms'
      PERMISSIONS:
        - 'hudson.model.Hudson.Read'
          # grant anon `admin` permissions for testing
        - 'hudson.model.Hudson.Administer'
      USERS:
        - 'anonymous'
    - NAME: 'jenkins admins'
      PERMISSIONS:
        - 'hudson.model.Computer.Build'
        - 'hudson.model.Computer.Configure'
        - 'hudson.model.Computer.Connect'
        - 'hudson.model.Computer.Create'
        - 'hudson.model.Computer.Delete'
        - 'hudson.model.Computer.Disconnect'
        - 'hudson.model.Hudson.Administer'
        - 'hudson.model.Hudson.ConfigureUpdateCenter'
        - 'hudson.model.Hudson.Read'
        - 'hudson.model.Hudson.RunScripts'
        - 'hudson.model.Hudson.UploadPlugins'
        - 'hudson.model.Item.Build'
        - 'hudson.model.Item.Cancel'
        - 'hudson.model.Item.Configure'
        - 'hudson.model.Item.Create'
        - 'hudson.model.Item.Delete'
        - 'hudson.model.Item.Discover'
        - 'hudson.model.Item.Read'
        - 'hudson.model.Item.Workspace'
        - 'hudson.model.Run.Delete'
        - 'hudson.model.Run.Update'
        - 'hudson.model.View.Configure'
        - 'hudson.model.View.Create'
        - 'hudson.model.View.Delete'
        - 'hudson.model.View.Read'
      USERS:
        - 'github-user1'
        - 'github-user2'
