---
SLACK_BASE_URL: 'https://www.example.com'
IS_SLACK_BOT: 'true'
SLACK_ROOM: 'myRoom'
SLACK_TEAM_DOMAIN: 'engineering'
# The following must be an id of a credential created in
# src/main/groovy/3importCredentials.groovy
SLACK_CREDENTIAL_ID: 'secretText1'
